version: '3'
services:
    database:
        image: 'mongo'
        container_name: 'database'
        restart: 'always'
        environment: 
            - MONGO_INITDB_DATABASE=vatstar
            - MONGO_INITDB_ROOT_USERNAME=mongodb
            - MONGO_INITDB_ROOT_PASSWORD=mongodb
        volumes: 
            - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
            - ./mongo-volume:/data/db
        ports:
            - '127.0.0.1:27017-27019:27017-27019'
    vatstar:
        build: ./discord
        container_name: 'discord'
        command: sh -c "npm install && npm run start-dev"
        working_dir: /root/discord
        volumes: 
        - ./:/root:cached
        environment: 
            - TOKEN
            - NODE_ENV=development
        depends_on: 
            - database
    frontend:
        container_name: frontend
        build: 
            context: ./frontend
            dockerfile: Dockerfile
        volumes: 
            - './frontend:/app'
            - '/app/node_modules'
        ports:
            - 3001:3000
        environment: 
            - CHOKIDAR_USEPOLLING=true
        stdin_open: true
        depends_on: 
            - backend
    backend:
        build: 
            context: ./backend
            dockerfile: Dockerfile
        container_name: backend
        command: sh -c "npm install && npm run tsnd"
        depends_on: 
            - database
        volumes:
            - './backend:/app'
            - '/app/node_modules'
        
        environment: 
            - NODE_ENV=development
            - MONGO_URI
            - MONGO_LOGIN
            - MONGO_PASSWORD