version: '3'
services:
    vatstar:
        build: ./discord
        command: sh -c "npm install && npm run start-dev"
        working_dir: /root/discord
        volumes: 
        - ./:/root:cached
        environment: 
            - TOKEN
            - NODE_ENV=development
        depends_on: 
            - database
    frontend:
        build: ./frontend
